repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
      - id: clang-format
        exclude: ^Assets/Scripts/Generated/.*  # Exclude generated files.
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 8.2.1
    hooks:
      - id: buildifier
        files: ^plugins/.*\.(bazel|bzl|BUILD)$  # Only apply to Bazel files in the plugins directory.
      - id: buildifier-lint
        files: ^plugins/.*\.(bazel|bzl|BUILD)$  # Only apply to Bazel files in the plugins directory.
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: protoc-cs
        name: protoc-cs
        entry: Assets/Proto/Scripts/compile.sh
        language: script
        pass_filenames: false
