repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        exclude: ^configs/.*\.cs$  # Exclude generated Protobuf .cs files.
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 8.0.1
    hooks:
      - id: buildifier
        files: ^plugins/.*\.(bazel|bzl|BUILD)$  # Only apply to Bazel files in the plugins directory.
      - id: buildifier-lint
        files: ^plugins/.*\.(bazel|bzl|BUILD)$  # Only apply to Bazel files in the plugins directory.
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
