# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: run_config.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'run_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10run_config.proto\x12\x07\x63onfigs\"\x84\x01\n\tRunConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x16simulation_config_file\x18\x02 \x01(\t\x12\x10\n\x08num_runs\x18\x03 \x01(\r\x12\x0c\n\x04seed\x18\x04 \x01(\x05\x12\x13\n\x0bseed_stride\x18\x05 \x01(\x05\x12\x14\n\x0cmax_parallel\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'run_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNCONFIG']._serialized_start=30
  _globals['_RUNCONFIG']._serialized_end=162
# @@protoc_insertion_point(module_scope)
