# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Configs/communication_config.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'Configs/communication_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Configs import static_config_pb2 as Configs_dot_static__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"Configs/communication_config.proto\x12\x07\x63onfigs\x1a\x1b\x43onfigs/static_config.proto\"a\n\nLinkConfig\x12\x17\n\x0flatency_seconds\x18\x01 \x01(\x02\x12\x1b\n\x13latency_std_seconds\x18\x02 \x01(\x02\x12\x1d\n\x15packet_delivery_ratio\x18\x03 \x01(\x02\"z\n\x0cLinkOverride\x12 \n\x04\x66rom\x18\x01 \x01(\x0e\x32\x12.configs.AgentType\x12\x1e\n\x02to\x18\x02 \x01(\x0e\x32\x12.configs.AgentType\x12(\n\x0blink_config\x18\x03 \x01(\x0b\x32\x13.configs.LinkConfig\"n\n\x13\x43ommunicationConfig\x12(\n\x0blink_config\x18\x01 \x01(\x0b\x32\x13.configs.LinkConfig\x12-\n\x0elink_overrides\x18\x02 \x03(\x0b\x32\x15.configs.LinkOverrideb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Configs.communication_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINKCONFIG']._serialized_start=76
  _globals['_LINKCONFIG']._serialized_end=173
  _globals['_LINKOVERRIDE']._serialized_start=175
  _globals['_LINKOVERRIDE']._serialized_end=297
  _globals['_COMMUNICATIONCONFIG']._serialized_start=299
  _globals['_COMMUNICATIONCONFIG']._serialized_end=409
# @@protoc_insertion_point(module_scope)
