# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Configs/run_config.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'Configs/run_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Configs import communication_config_pb2 as Configs_dot_communication__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43onfigs/run_config.proto\x12\x07\x63onfigs\x1a\"Configs/communication_config.proto\"a\n\x15\x43ommunicationScenario\x12\x0c\n\x04name\x18\x01 \x01(\t\x12:\n\x14\x63ommunication_config\x18\x02 \x01(\x0b\x32\x1c.configs.CommunicationConfig\"\xc5\x01\n\tRunConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x16simulation_config_file\x18\x02 \x01(\t\x12\x10\n\x08num_runs\x18\x03 \x01(\r\x12\x0c\n\x04seed\x18\x04 \x01(\x05\x12\x13\n\x0bseed_stride\x18\x05 \x01(\x05\x12\x14\n\x0cmax_parallel\x18\x06 \x01(\r\x12?\n\x17\x63ommunication_scenarios\x18\x07 \x03(\x0b\x32\x1e.configs.CommunicationScenariob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Configs.run_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMUNICATIONSCENARIO']._serialized_start=73
  _globals['_COMMUNICATIONSCENARIO']._serialized_end=170
  _globals['_RUNCONFIG']._serialized_start=173
  _globals['_RUNCONFIG']._serialized_end=370
# @@protoc_insertion_point(module_scope)
