enable_telemetry_logging: false
enable_event_logging: true
enable_missile_trail_effect: false
enable_explosion_effect: false
physics_update_rate: 500
persistent_flight_trails: true

communication_config {
  mailbox_config {
    latency_mode: INDIVIDUAL_LATENCY
    latency_jitter_std_seconds: 0.02

    latency_overrides { from: MAILBOX_NODE_IADS to: MAILBOX_NODE_CARRIER seconds: 0.10 }
    latency_overrides { from: MAILBOX_NODE_CARRIER to: MAILBOX_NODE_IADS seconds: 0.10 }
    latency_overrides { from: MAILBOX_NODE_CARRIER to: MAILBOX_NODE_INTERCEPTOR seconds: 0.25 }
    latency_overrides { from: MAILBOX_NODE_INTERCEPTOR to: MAILBOX_NODE_CARRIER seconds: 0.15 }
    latency_overrides { from: MAILBOX_NODE_INTERCEPTOR to: MAILBOX_NODE_INTERCEPTOR seconds: 0.05 }
  }
}
