// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: configs/proto/agent.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Micromissiles {

  /// <summary>Holder for reflection information generated from configs/proto/agent.proto</summary>
  public static partial class AgentReflection {

    #region Descriptor
    /// <summary>File descriptor for configs/proto/agent.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AgentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chljb25maWdzL3Byb3RvL2FnZW50LnByb3RvEg1taWNyb21pc3NpbGVzGiJj",
            "b25maWdzL3Byb3RvL2R5bmFtaWNfY29uZmlnLnByb3RvGhljb25maWdzL3By",
            "b3RvL3N0YXRlLnByb3RvIswDCgtBZ2VudENvbmZpZxI6ChBpbnRlcmNlcHRv",
            "cl90eXBlGAEgASgOMh4ubWljcm9taXNzaWxlcy5JbnRlcmNlcHRvclR5cGVI",
            "ABIwCgt0aHJlYXRfdHlwZRgCIAEoDjIZLm1pY3JvbWlzc2lsZXMuVGhyZWF0",
            "VHlwZUgAEisKDWluaXRpYWxfc3RhdGUYAyABKAsyFC5taWNyb21pc3NpbGVz",
            "LlN0YXRlEjAKEnN0YW5kYXJkX2RldmlhdGlvbhgEIAEoCzIULm1pY3JvbWlz",
            "c2lsZXMuU3RhdGUSNAoOZHluYW1pY19jb25maWcYBSABKAsyHC5taWNyb21p",
            "c3NpbGVzLkR5bmFtaWNDb25maWcSSgoTc3VibXVuaXRpb25zX2NvbmZpZxgG",
            "IAEoCzItLm1pY3JvbWlzc2lsZXMuQWdlbnRDb25maWcuU3VibXVuaXRpb25z",
            "Q29uZmlnGmAKElN1Ym11bml0aW9uc0NvbmZpZxIYChBudW1fc3VibXVuaXRp",
            "b25zGAEgASgNEjAKDGFnZW50X2NvbmZpZxgCIAEoCzIaLm1pY3JvbWlzc2ls",
            "ZXMuQWdlbnRDb25maWdCDAoKdHlwZV9vbmVvZiJYChBBZ2VudFN3YXJtQ29u",
            "ZmlnEhIKCm51bV9hZ2VudHMYASABKA0SMAoMYWdlbnRfY29uZmlnGAIgASgL",
            "MhoubWljcm9taXNzaWxlcy5BZ2VudENvbmZpZyoxCg9JbnRlcmNlcHRvclR5",
            "cGUSEAoMTUlDUk9NSVNTSUxFEAASDAoISFlEUkFfNzAQASomCgpUaHJlYXRU",
            "eXBlEg4KClFVQURDT1BURVIQABIICgRVQ0FWEAEqYQoLRmxpZ2h0UGhhc2US",
            "DwoLSU5JVElBTElaRUQQABIJCgVSRUFEWRABEgkKBUJPT1NUEAISDQoJTUlE",
            "Q09VUlNFEAMSDAoIVEVSTUlOQUwQBBIOCgpURVJNSU5BVEVEEAViBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Micromissiles.DynamicConfigReflection.Descriptor, global::Micromissiles.StateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Micromissiles.InterceptorType), typeof(global::Micromissiles.ThreatType), typeof(global::Micromissiles.FlightPhase), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Micromissiles.AgentConfig), global::Micromissiles.AgentConfig.Parser, new[]{ "InterceptorType", "ThreatType", "InitialState", "StandardDeviation", "DynamicConfig", "SubmunitionsConfig" }, new[]{ "TypeOneof" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Micromissiles.AgentConfig.Types.SubmunitionsConfig), global::Micromissiles.AgentConfig.Types.SubmunitionsConfig.Parser, new[]{ "NumSubmunitions", "AgentConfig" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Micromissiles.AgentSwarmConfig), global::Micromissiles.AgentSwarmConfig.Parser, new[]{ "NumAgents", "AgentConfig" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Interceptor type enumeration.
  /// </summary>
  public enum InterceptorType {
    [pbr::OriginalName("MICROMISSILE")] Micromissile = 0,
    [pbr::OriginalName("HYDRA_70")] Hydra70 = 1,
  }

  /// <summary>
  /// Threat type enumeration.
  /// </summary>
  public enum ThreatType {
    [pbr::OriginalName("QUADCOPTER")] Quadcopter = 0,
    [pbr::OriginalName("UCAV")] Ucav = 1,
  }

  /// <summary>
  /// Flight phase enumeration.
  /// </summary>
  public enum FlightPhase {
    [pbr::OriginalName("INITIALIZED")] Initialized = 0,
    [pbr::OriginalName("READY")] Ready = 1,
    [pbr::OriginalName("BOOST")] Boost = 2,
    [pbr::OriginalName("MIDCOURSE")] Midcourse = 3,
    [pbr::OriginalName("TERMINAL")] Terminal = 4,
    [pbr::OriginalName("TERMINATED")] Terminated = 5,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Agent configuration.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AgentConfig : pb::IMessage<AgentConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AgentConfig> _parser = new pb::MessageParser<AgentConfig>(() => new AgentConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AgentConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Micromissiles.AgentReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentConfig(AgentConfig other) : this() {
      initialState_ = other.initialState_ != null ? other.initialState_.Clone() : null;
      standardDeviation_ = other.standardDeviation_ != null ? other.standardDeviation_.Clone() : null;
      dynamicConfig_ = other.dynamicConfig_ != null ? other.dynamicConfig_.Clone() : null;
      submunitionsConfig_ = other.submunitionsConfig_ != null ? other.submunitionsConfig_.Clone() : null;
      switch (other.TypeOneofCase) {
        case TypeOneofOneofCase.InterceptorType:
          InterceptorType = other.InterceptorType;
          break;
        case TypeOneofOneofCase.ThreatType:
          ThreatType = other.ThreatType;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentConfig Clone() {
      return new AgentConfig(this);
    }

    /// <summary>Field number for the "interceptor_type" field.</summary>
    public const int InterceptorTypeFieldNumber = 1;
    /// <summary>
    /// Interceptor type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.InterceptorType InterceptorType {
      get { return HasInterceptorType ? (global::Micromissiles.InterceptorType) typeOneof_ : global::Micromissiles.InterceptorType.Micromissile; }
      set {
        typeOneof_ = value;
        typeOneofCase_ = TypeOneofOneofCase.InterceptorType;
      }
    }
    /// <summary>Gets whether the "interceptor_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasInterceptorType {
      get { return typeOneofCase_ == TypeOneofOneofCase.InterceptorType; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "interceptor_type" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInterceptorType() {
      if (HasInterceptorType) {
        ClearTypeOneof();
      }
    }

    /// <summary>Field number for the "threat_type" field.</summary>
    public const int ThreatTypeFieldNumber = 2;
    /// <summary>
    /// Threat type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.ThreatType ThreatType {
      get { return HasThreatType ? (global::Micromissiles.ThreatType) typeOneof_ : global::Micromissiles.ThreatType.Quadcopter; }
      set {
        typeOneof_ = value;
        typeOneofCase_ = TypeOneofOneofCase.ThreatType;
      }
    }
    /// <summary>Gets whether the "threat_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasThreatType {
      get { return typeOneofCase_ == TypeOneofOneofCase.ThreatType; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "threat_type" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearThreatType() {
      if (HasThreatType) {
        ClearTypeOneof();
      }
    }

    /// <summary>Field number for the "initial_state" field.</summary>
    public const int InitialStateFieldNumber = 3;
    private global::Micromissiles.State initialState_;
    /// <summary>
    /// Initial state.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.State InitialState {
      get { return initialState_; }
      set {
        initialState_ = value;
      }
    }

    /// <summary>Field number for the "standard_deviation" field.</summary>
    public const int StandardDeviationFieldNumber = 4;
    private global::Micromissiles.State standardDeviation_;
    /// <summary>
    /// Initial state standard deviation to randomize the state variables.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.State StandardDeviation {
      get { return standardDeviation_; }
      set {
        standardDeviation_ = value;
      }
    }

    /// <summary>Field number for the "dynamic_config" field.</summary>
    public const int DynamicConfigFieldNumber = 5;
    private global::Micromissiles.DynamicConfig dynamicConfig_;
    /// <summary>
    /// Dynamic configuration.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.DynamicConfig DynamicConfig {
      get { return dynamicConfig_; }
      set {
        dynamicConfig_ = value;
      }
    }

    /// <summary>Field number for the "submunitions_config" field.</summary>
    public const int SubmunitionsConfigFieldNumber = 6;
    private global::Micromissiles.AgentConfig.Types.SubmunitionsConfig submunitionsConfig_;
    /// <summary>
    /// Submunitions configuration.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.AgentConfig.Types.SubmunitionsConfig SubmunitionsConfig {
      get { return submunitionsConfig_; }
      set {
        submunitionsConfig_ = value;
      }
    }

    private object typeOneof_;
    /// <summary>Enum of possible cases for the "type_oneof" oneof.</summary>
    public enum TypeOneofOneofCase {
      None = 0,
      InterceptorType = 1,
      ThreatType = 2,
    }
    private TypeOneofOneofCase typeOneofCase_ = TypeOneofOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TypeOneofOneofCase TypeOneofCase {
      get { return typeOneofCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTypeOneof() {
      typeOneofCase_ = TypeOneofOneofCase.None;
      typeOneof_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AgentConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AgentConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InterceptorType != other.InterceptorType) return false;
      if (ThreatType != other.ThreatType) return false;
      if (!object.Equals(InitialState, other.InitialState)) return false;
      if (!object.Equals(StandardDeviation, other.StandardDeviation)) return false;
      if (!object.Equals(DynamicConfig, other.DynamicConfig)) return false;
      if (!object.Equals(SubmunitionsConfig, other.SubmunitionsConfig)) return false;
      if (TypeOneofCase != other.TypeOneofCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasInterceptorType) hash ^= InterceptorType.GetHashCode();
      if (HasThreatType) hash ^= ThreatType.GetHashCode();
      if (initialState_ != null) hash ^= InitialState.GetHashCode();
      if (standardDeviation_ != null) hash ^= StandardDeviation.GetHashCode();
      if (dynamicConfig_ != null) hash ^= DynamicConfig.GetHashCode();
      if (submunitionsConfig_ != null) hash ^= SubmunitionsConfig.GetHashCode();
      hash ^= (int) typeOneofCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasInterceptorType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) InterceptorType);
      }
      if (HasThreatType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ThreatType);
      }
      if (initialState_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(InitialState);
      }
      if (standardDeviation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(StandardDeviation);
      }
      if (dynamicConfig_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(DynamicConfig);
      }
      if (submunitionsConfig_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(SubmunitionsConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasInterceptorType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) InterceptorType);
      }
      if (HasThreatType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ThreatType);
      }
      if (initialState_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(InitialState);
      }
      if (standardDeviation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(StandardDeviation);
      }
      if (dynamicConfig_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(DynamicConfig);
      }
      if (submunitionsConfig_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(SubmunitionsConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasInterceptorType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) InterceptorType);
      }
      if (HasThreatType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ThreatType);
      }
      if (initialState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InitialState);
      }
      if (standardDeviation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StandardDeviation);
      }
      if (dynamicConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DynamicConfig);
      }
      if (submunitionsConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SubmunitionsConfig);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AgentConfig other) {
      if (other == null) {
        return;
      }
      if (other.initialState_ != null) {
        if (initialState_ == null) {
          InitialState = new global::Micromissiles.State();
        }
        InitialState.MergeFrom(other.InitialState);
      }
      if (other.standardDeviation_ != null) {
        if (standardDeviation_ == null) {
          StandardDeviation = new global::Micromissiles.State();
        }
        StandardDeviation.MergeFrom(other.StandardDeviation);
      }
      if (other.dynamicConfig_ != null) {
        if (dynamicConfig_ == null) {
          DynamicConfig = new global::Micromissiles.DynamicConfig();
        }
        DynamicConfig.MergeFrom(other.DynamicConfig);
      }
      if (other.submunitionsConfig_ != null) {
        if (submunitionsConfig_ == null) {
          SubmunitionsConfig = new global::Micromissiles.AgentConfig.Types.SubmunitionsConfig();
        }
        SubmunitionsConfig.MergeFrom(other.SubmunitionsConfig);
      }
      switch (other.TypeOneofCase) {
        case TypeOneofOneofCase.InterceptorType:
          InterceptorType = other.InterceptorType;
          break;
        case TypeOneofOneofCase.ThreatType:
          ThreatType = other.ThreatType;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            typeOneof_ = input.ReadEnum();
            typeOneofCase_ = TypeOneofOneofCase.InterceptorType;
            break;
          }
          case 16: {
            typeOneof_ = input.ReadEnum();
            typeOneofCase_ = TypeOneofOneofCase.ThreatType;
            break;
          }
          case 26: {
            if (initialState_ == null) {
              InitialState = new global::Micromissiles.State();
            }
            input.ReadMessage(InitialState);
            break;
          }
          case 34: {
            if (standardDeviation_ == null) {
              StandardDeviation = new global::Micromissiles.State();
            }
            input.ReadMessage(StandardDeviation);
            break;
          }
          case 42: {
            if (dynamicConfig_ == null) {
              DynamicConfig = new global::Micromissiles.DynamicConfig();
            }
            input.ReadMessage(DynamicConfig);
            break;
          }
          case 50: {
            if (submunitionsConfig_ == null) {
              SubmunitionsConfig = new global::Micromissiles.AgentConfig.Types.SubmunitionsConfig();
            }
            input.ReadMessage(SubmunitionsConfig);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            typeOneof_ = input.ReadEnum();
            typeOneofCase_ = TypeOneofOneofCase.InterceptorType;
            break;
          }
          case 16: {
            typeOneof_ = input.ReadEnum();
            typeOneofCase_ = TypeOneofOneofCase.ThreatType;
            break;
          }
          case 26: {
            if (initialState_ == null) {
              InitialState = new global::Micromissiles.State();
            }
            input.ReadMessage(InitialState);
            break;
          }
          case 34: {
            if (standardDeviation_ == null) {
              StandardDeviation = new global::Micromissiles.State();
            }
            input.ReadMessage(StandardDeviation);
            break;
          }
          case 42: {
            if (dynamicConfig_ == null) {
              DynamicConfig = new global::Micromissiles.DynamicConfig();
            }
            input.ReadMessage(DynamicConfig);
            break;
          }
          case 50: {
            if (submunitionsConfig_ == null) {
              SubmunitionsConfig = new global::Micromissiles.AgentConfig.Types.SubmunitionsConfig();
            }
            input.ReadMessage(SubmunitionsConfig);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AgentConfig message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Submunitions configuration.
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class SubmunitionsConfig : pb::IMessage<SubmunitionsConfig>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<SubmunitionsConfig> _parser = new pb::MessageParser<SubmunitionsConfig>(() => new SubmunitionsConfig());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SubmunitionsConfig> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Micromissiles.AgentConfig.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SubmunitionsConfig() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SubmunitionsConfig(SubmunitionsConfig other) : this() {
          numSubmunitions_ = other.numSubmunitions_;
          agentConfig_ = other.agentConfig_ != null ? other.agentConfig_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SubmunitionsConfig Clone() {
          return new SubmunitionsConfig(this);
        }

        /// <summary>Field number for the "num_submunitions" field.</summary>
        public const int NumSubmunitionsFieldNumber = 1;
        private uint numSubmunitions_;
        /// <summary>
        /// Number of submunitions.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint NumSubmunitions {
          get { return numSubmunitions_; }
          set {
            numSubmunitions_ = value;
          }
        }

        /// <summary>Field number for the "agent_config" field.</summary>
        public const int AgentConfigFieldNumber = 2;
        private global::Micromissiles.AgentConfig agentConfig_;
        /// <summary>
        /// Agent configuration.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Micromissiles.AgentConfig AgentConfig {
          get { return agentConfig_; }
          set {
            agentConfig_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as SubmunitionsConfig);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SubmunitionsConfig other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (NumSubmunitions != other.NumSubmunitions) return false;
          if (!object.Equals(AgentConfig, other.AgentConfig)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (NumSubmunitions != 0) hash ^= NumSubmunitions.GetHashCode();
          if (agentConfig_ != null) hash ^= AgentConfig.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (NumSubmunitions != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(NumSubmunitions);
          }
          if (agentConfig_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(AgentConfig);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (NumSubmunitions != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(NumSubmunitions);
          }
          if (agentConfig_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(AgentConfig);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (NumSubmunitions != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumSubmunitions);
          }
          if (agentConfig_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(AgentConfig);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SubmunitionsConfig other) {
          if (other == null) {
            return;
          }
          if (other.NumSubmunitions != 0) {
            NumSubmunitions = other.NumSubmunitions;
          }
          if (other.agentConfig_ != null) {
            if (agentConfig_ == null) {
              AgentConfig = new global::Micromissiles.AgentConfig();
            }
            AgentConfig.MergeFrom(other.AgentConfig);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                NumSubmunitions = input.ReadUInt32();
                break;
              }
              case 18: {
                if (agentConfig_ == null) {
                  AgentConfig = new global::Micromissiles.AgentConfig();
                }
                input.ReadMessage(AgentConfig);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                NumSubmunitions = input.ReadUInt32();
                break;
              }
              case 18: {
                if (agentConfig_ == null) {
                  AgentConfig = new global::Micromissiles.AgentConfig();
                }
                input.ReadMessage(AgentConfig);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  /// <summary>
  /// Agent swarm configuration.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AgentSwarmConfig : pb::IMessage<AgentSwarmConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AgentSwarmConfig> _parser = new pb::MessageParser<AgentSwarmConfig>(() => new AgentSwarmConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AgentSwarmConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Micromissiles.AgentReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentSwarmConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentSwarmConfig(AgentSwarmConfig other) : this() {
      numAgents_ = other.numAgents_;
      agentConfig_ = other.agentConfig_ != null ? other.agentConfig_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentSwarmConfig Clone() {
      return new AgentSwarmConfig(this);
    }

    /// <summary>Field number for the "num_agents" field.</summary>
    public const int NumAgentsFieldNumber = 1;
    private uint numAgents_;
    /// <summary>
    /// Number of agents.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NumAgents {
      get { return numAgents_; }
      set {
        numAgents_ = value;
      }
    }

    /// <summary>Field number for the "agent_config" field.</summary>
    public const int AgentConfigFieldNumber = 2;
    private global::Micromissiles.AgentConfig agentConfig_;
    /// <summary>
    /// Agent configuration.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.AgentConfig AgentConfig {
      get { return agentConfig_; }
      set {
        agentConfig_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AgentSwarmConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AgentSwarmConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumAgents != other.NumAgents) return false;
      if (!object.Equals(AgentConfig, other.AgentConfig)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NumAgents != 0) hash ^= NumAgents.GetHashCode();
      if (agentConfig_ != null) hash ^= AgentConfig.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NumAgents != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(NumAgents);
      }
      if (agentConfig_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AgentConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NumAgents != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(NumAgents);
      }
      if (agentConfig_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AgentConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NumAgents != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumAgents);
      }
      if (agentConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AgentConfig);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AgentSwarmConfig other) {
      if (other == null) {
        return;
      }
      if (other.NumAgents != 0) {
        NumAgents = other.NumAgents;
      }
      if (other.agentConfig_ != null) {
        if (agentConfig_ == null) {
          AgentConfig = new global::Micromissiles.AgentConfig();
        }
        AgentConfig.MergeFrom(other.AgentConfig);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NumAgents = input.ReadUInt32();
            break;
          }
          case 18: {
            if (agentConfig_ == null) {
              AgentConfig = new global::Micromissiles.AgentConfig();
            }
            input.ReadMessage(AgentConfig);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NumAgents = input.ReadUInt32();
            break;
          }
          case 18: {
            if (agentConfig_ == null) {
              AgentConfig = new global::Micromissiles.AgentConfig();
            }
            input.ReadMessage(AgentConfig);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
