name: "Anti-Ship Cruise Missile"
type: FIXED_WING_THREAT
cost: 30000
acceleration_config {
  max_forward_acceleration: 1
  max_reference_normal_acceleration: 10
  reference_speed: 300
}
body_config {
  mass: 10
}
hit_config {
  hit_radius: 1
  kill_probability: 0.8
}
power_table {
  power: IDLE
  speed: 0
}
power_table {
  power: LOW
  speed: 40
}
power_table {
  power: CRUISE
  speed: 300
}
power_table {
  power: MIL
  speed: 300
}
power_table {
  power: MAX
  speed: 300
}
visualization_config {
  symbol_present: "hostile_missile_cruise_present"
  symbol_destroyed: "hostile_missile_cruise_destroyed"
}
