name: "BrahMos Direct Attack"
type: DIRECT_ATTACK
target_position {
  x: 0.01
  y: 0
  z: 0
}
target_velocity {
  x: 0.0001
  y: 0
  z: 0
}
target_collider_size {
  x: 20
  y: 20
  z: 20
}
flight_plan {
  type: DISTANCE_TO_TARGET
  waypoints {
    distance: 100000
    altitude: 500
    power: MIL
  }
  waypoints {
    distance: 10000
    altitude: 500
    power: MIL
  }
  waypoints {
    distance: 8000
    altitude: 500
    power: MIL
  }
  waypoints {
    distance: 5000
    altitude: 500
    power: MAX
  }
}
