name: "Fateh 110B Direct Attack"
type: DIRECT_ATTACK
target_position {
  x: 0.01
  y: 0
  z: 0
}
target_velocity {
  x: 0.0001
  y: 0
  z: 0
}
target_collider_size {
  x: 20
  y: 20
  z: 20
}
flight_plan {
  type: DISTANCE_TO_TARGET
  waypoints {
    distance: 20
    altitude: 0
    power: MAX
  }
  waypoints {
    distance: 10
    altitude: 0
    power: MAX
  }
}
