end_time: 300
time_scale: 1
interceptor_swarm_configs {
  agent_config {
    config_file: "ddg.pbtxt"
    initial_state {
      position {
        x: 0
        y: 0
        z: 0
      }
      velocity {
        x: 5
        y: 0
        z: 0
      }
    }
    dynamic_config {
      sensor_config {
        type: IDEAL
        frequency: 1000
      }
    }
    sub_agent_config {
      num_sub_agents: 126
      agent_config {
        config_file: "hydra70.pbtxt"
        dynamic_config {
          flight_config {
            controller_type: PROPORTIONAL_NAVIGATION
          }
          sensor_config {
            type: IDEAL
            frequency: 100
          }
        }
        sub_agent_config {
          num_sub_agents: 7
          agent_config: {
            config_file: "micromissile.pbtxt"
            dynamic_config {
              flight_config {
                controller_type: PROPORTIONAL_NAVIGATION
              }
              sensor_config {
                type: IDEAL
                frequency: 100
              }
            }
          }
        }
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 20
  agent_config {
    config_file: "ucav.pbtxt"
    attack_behavior_config_file: "default_direct_attack.pbtxt"
    initial_state {
      position {
        x: 0
        y: 800
        z: 10000
      }
      velocity {
        x: 0
        y: 0
        z: -100
      }
    }
    standard_deviation {
      position {
        x: 1000
        y: 200
        z: 100
      }
      velocity {
        x: 0
        y: 0
        z: 25
      }
    }
    dynamic_config {
      flight_config {
        evasion_config {
            enabled: true
            range_threshold: 1000
        }
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 20
  agent_config {
    config_file: "ucav.pbtxt"
    attack_behavior_config_file: "default_direct_attack.pbtxt"
    initial_state {
      position {
        x: 0
        y: 900
        z: 11000
      }
      velocity {
        x: 0
        y: 0
        z: -100
      }
    }
    standard_deviation {
      position {
        x: 1000
        y: 200
        z: 100
      }
      velocity {
        x: 0
        y: 0
        z: 25
      }
    }
    dynamic_config {
      flight_config {
        evasion_config {
            enabled: true
            range_threshold: 1000
        }
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 20
  agent_config {
    config_file: "ucav.pbtxt"
    attack_behavior_config_file: "default_direct_attack.pbtxt"
    initial_state {
      position {
        x: 0
        y: 1000
        z: 12000
      }
      velocity {
        x: 0
        y: 0
        z: -100
      }
    }
    standard_deviation {
      position {
        x: 1000
        y: 200
        z: 100
      }
      velocity {
        x: 0
        y: 0
        z: 25
      }
    }
    dynamic_config {
      flight_config {
        evasion_config {
            enabled: true
            range_threshold: 1000
        }
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 20
  agent_config {
    config_file: "ucav.pbtxt"
    attack_behavior_config_file: "default_direct_attack.pbtxt"
    initial_state {
      position {
        x: 0
        y: 1100
        z: 13000
      }
      velocity {
        x: 0
        y: 0
        z: -100
      }
    }
    standard_deviation {
      position {
        x: 1000
        y: 200
        z: 100
      }
      velocity {
        x: 0
        y: 0
        z: 25
      }
    }
    dynamic_config {
      flight_config {
        evasion_config {
            enabled: true
            range_threshold: 1000
        }
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 20
  agent_config {
    config_file: "ucav.pbtxt"
    attack_behavior_config_file: "default_direct_attack.pbtxt"
    initial_state {
      position {
        x: 0
        y: 1200
        z: 14000
      }
      velocity {
        x: 0
        y: 0
        z: -100
      }
    }
    standard_deviation {
      position {
        x: 1000
        y: 200
        z: 100
      }
      velocity {
        x: 0
        y: 0
        z: 25
      }
    }
    dynamic_config {
      flight_config {
        evasion_config {
            enabled: true
            range_threshold: 1000
        }
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
  }
}
