end_time: 300
time_scale: 1
interceptor_swarm_configs {
  agent_config {
    config_file: "hydra70.pbtxt"
    dynamic_config {
      flight_config {
        controller_type: PROPORTIONAL_NAVIGATION
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
    submunitions_config {
      num_submunitions: 7
      agent_config: {
        config_file: "micromissile.pbtxt"
        dynamic_config {
          flight_config {
            controller_type: PROPORTIONAL_NAVIGATION
          }
          sensor_config {
            type: IDEAL
            frequency: 100
          }
        }
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 7
  agent_config {
    config_file: "brahmos.pbtxt"
    attack_behavior_config_file: "brahmos_direct_attack.json"
    initial_state {
      position {
        x: 0
        y: 50
        z: 30000
      }
      velocity {
        x: 0
        y: 0
        z: -800
      }
    }
    standard_deviation {
      position {
        x: 3000
        y: 10
        z: 200
      }
      velocity {
        x: 0
        y: 0
        z: 25
      }
    }
    dynamic_config {
      flight_config {
        evasion_config {
            enabled: true
            range_threshold: 2000
        }
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 7
  agent_config {
    config_file: "brahmos.pbtxt"
    attack_behavior_config_file: "brahmos_direct_attack.json"
    initial_state {
      position {
        x: 0
        y: 50
        z: 35000
      }
      velocity {
        x: 0
        y: 0
        z: -800
      }
    }
    standard_deviation {
      position {
        x: 3000
        y: 200
        z: 100
      }
      velocity {
        x: 0
        y: 0
        z: 25
      }
    }
    dynamic_config {
      flight_config {
        evasion_config {
            enabled: true
            range_threshold: 2000
        }
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 7
  agent_config {
    config_file: "brahmos.pbtxt"
    attack_behavior_config_file: "brahmos_direct_attack.json"
    initial_state {
      position {
        x: 0
        y: 50
        z: 40000
      }
      velocity {
        x: 0
        y: 0
        z: -800
      }
    }
    standard_deviation {
      position {
        x: 3000
        y: 10
        z: 200
      }
      velocity {
        x: 0
        y: 0
        z: 25
      }
    }
    dynamic_config {
      flight_config {
        evasion_config {
            enabled: true
            range_threshold: 2000
        }
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 7
  agent_config {
    config_file: "brahmos.pbtxt"
    attack_behavior_config_file: "brahmos_direct_attack.json"
    initial_state {
      position {
        x: 0
        y: 50
        z: 45000
      }
      velocity {
        x: 0
        y: 0
        z: -800
      }
    }
    standard_deviation {
      position {
        x: 3000
        y: 10
        z: 200
      }
      velocity {
        x: 0
        y: 0
        z: 25
      }
    }
    dynamic_config {
      flight_config {
        evasion_config {
            enabled: true
            range_threshold: 2000
        }
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
  }
}
threat_swarm_configs {
  num_agents: 7
  agent_config {
    config_file: "brahmos.pbtxt"
    attack_behavior_config_file: "brahmos_direct_attack.json"
    initial_state {
      position {
        x: 0
        y: 50
        z: 50000
      }
      velocity {
        x: 0
        y: 0
        z: -800
      }
    }
    standard_deviation {
      position {
        x: 3000
        y: 10
        z: 200
      }
      velocity {
        x: 0
        y: 0
        z: 25
      }
    }
    dynamic_config {
      flight_config {
        evasion_config {
            enabled: true
            range_threshold: 2000
        }
      }
      sensor_config {
        type: IDEAL
        frequency: 100
      }
    }
  }
}
