// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: configs/proto/dynamic_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Micromissiles {

  /// <summary>Holder for reflection information generated from configs/proto/dynamic_config.proto</summary>
  public static partial class DynamicConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for configs/proto/dynamic_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DynamicConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJjb25maWdzL3Byb3RvL2R5bmFtaWNfY29uZmlnLnByb3RvEg1taWNyb21p",
            "c3NpbGVzGhpjb25maWdzL3Byb3RvL3NlbnNvci5wcm90byK4AQoMRmxpZ2h0",
            "Q29uZmlnEjEKCmNvbnRyb2xsZXIYASABKA4yHS5taWNyb21pc3NpbGVzLkNv",
            "bnRyb2xsZXJUeXBlEjoKB2V2YXNpb24YAiABKAsyKS5taWNyb21pc3NpbGVz",
            "LkZsaWdodENvbmZpZy5FdmFzaW9uQ29uZmlnGjkKDUV2YXNpb25Db25maWcS",
            "DwoHZW5hYmxlZBgBIAEoCBIXCg9yYW5nZV90aHJlc2hvbGQYAiABKAIidwoN",
            "RHluYW1pY0NvbmZpZxIyCg1mbGlnaHRfY29uZmlnGAEgASgLMhsubWljcm9t",
            "aXNzaWxlcy5GbGlnaHRDb25maWcSMgoNc2Vuc29yX2NvbmZpZxgCIAEoCzIb",
            "Lm1pY3JvbWlzc2lsZXMuU2Vuc29yQ29uZmlnKlQKDkNvbnRyb2xsZXJUeXBl",
            "EhsKF1BST1BPUlRJT05BTF9OQVZJR0FUSU9OEAASJQohQVVHTUVOVEVEX1BS",
            "T1BPUlRJT05BTF9OQVZJR0FUSU9OEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Micromissiles.SensorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Micromissiles.ControllerType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Micromissiles.FlightConfig), global::Micromissiles.FlightConfig.Parser, new[]{ "Controller", "Evasion" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Micromissiles.FlightConfig.Types.EvasionConfig), global::Micromissiles.FlightConfig.Types.EvasionConfig.Parser, new[]{ "Enabled", "RangeThreshold" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Micromissiles.DynamicConfig), global::Micromissiles.DynamicConfig.Parser, new[]{ "FlightConfig", "SensorConfig" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Controller type enumeration.
  /// </summary>
  public enum ControllerType {
    [pbr::OriginalName("PROPORTIONAL_NAVIGATION")] ProportionalNavigation = 0,
    [pbr::OriginalName("AUGMENTED_PROPORTIONAL_NAVIGATION")] AugmentedProportionalNavigation = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Flight configuration.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FlightConfig : pb::IMessage<FlightConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FlightConfig> _parser = new pb::MessageParser<FlightConfig>(() => new FlightConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FlightConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Micromissiles.DynamicConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FlightConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FlightConfig(FlightConfig other) : this() {
      controller_ = other.controller_;
      evasion_ = other.evasion_ != null ? other.evasion_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FlightConfig Clone() {
      return new FlightConfig(this);
    }

    /// <summary>Field number for the "controller" field.</summary>
    public const int ControllerFieldNumber = 1;
    private global::Micromissiles.ControllerType controller_ = global::Micromissiles.ControllerType.ProportionalNavigation;
    /// <summary>
    /// Controller type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.ControllerType Controller {
      get { return controller_; }
      set {
        controller_ = value;
      }
    }

    /// <summary>Field number for the "evasion" field.</summary>
    public const int EvasionFieldNumber = 2;
    private global::Micromissiles.FlightConfig.Types.EvasionConfig evasion_;
    /// <summary>
    /// Evasion configuration.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.FlightConfig.Types.EvasionConfig Evasion {
      get { return evasion_; }
      set {
        evasion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FlightConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FlightConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Controller != other.Controller) return false;
      if (!object.Equals(Evasion, other.Evasion)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Controller != global::Micromissiles.ControllerType.ProportionalNavigation) hash ^= Controller.GetHashCode();
      if (evasion_ != null) hash ^= Evasion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Controller != global::Micromissiles.ControllerType.ProportionalNavigation) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Controller);
      }
      if (evasion_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Evasion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Controller != global::Micromissiles.ControllerType.ProportionalNavigation) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Controller);
      }
      if (evasion_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Evasion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Controller != global::Micromissiles.ControllerType.ProportionalNavigation) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Controller);
      }
      if (evasion_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Evasion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FlightConfig other) {
      if (other == null) {
        return;
      }
      if (other.Controller != global::Micromissiles.ControllerType.ProportionalNavigation) {
        Controller = other.Controller;
      }
      if (other.evasion_ != null) {
        if (evasion_ == null) {
          Evasion = new global::Micromissiles.FlightConfig.Types.EvasionConfig();
        }
        Evasion.MergeFrom(other.Evasion);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Controller = (global::Micromissiles.ControllerType) input.ReadEnum();
            break;
          }
          case 18: {
            if (evasion_ == null) {
              Evasion = new global::Micromissiles.FlightConfig.Types.EvasionConfig();
            }
            input.ReadMessage(Evasion);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Controller = (global::Micromissiles.ControllerType) input.ReadEnum();
            break;
          }
          case 18: {
            if (evasion_ == null) {
              Evasion = new global::Micromissiles.FlightConfig.Types.EvasionConfig();
            }
            input.ReadMessage(Evasion);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the FlightConfig message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Evasion configuration.
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class EvasionConfig : pb::IMessage<EvasionConfig>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<EvasionConfig> _parser = new pb::MessageParser<EvasionConfig>(() => new EvasionConfig());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<EvasionConfig> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Micromissiles.FlightConfig.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EvasionConfig() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EvasionConfig(EvasionConfig other) : this() {
          enabled_ = other.enabled_;
          rangeThreshold_ = other.rangeThreshold_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EvasionConfig Clone() {
          return new EvasionConfig(this);
        }

        /// <summary>Field number for the "enabled" field.</summary>
        public const int EnabledFieldNumber = 1;
        private bool enabled_;
        /// <summary>
        /// If true, evasion is enabled.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Enabled {
          get { return enabled_; }
          set {
            enabled_ = value;
          }
        }

        /// <summary>Field number for the "range_threshold" field.</summary>
        public const int RangeThresholdFieldNumber = 2;
        private float rangeThreshold_;
        /// <summary>
        /// Range threshold in m at which the agent should evade.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float RangeThreshold {
          get { return rangeThreshold_; }
          set {
            rangeThreshold_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as EvasionConfig);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(EvasionConfig other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Enabled != other.Enabled) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RangeThreshold, other.RangeThreshold)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Enabled != false) hash ^= Enabled.GetHashCode();
          if (RangeThreshold != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RangeThreshold);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Enabled != false) {
            output.WriteRawTag(8);
            output.WriteBool(Enabled);
          }
          if (RangeThreshold != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(RangeThreshold);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Enabled != false) {
            output.WriteRawTag(8);
            output.WriteBool(Enabled);
          }
          if (RangeThreshold != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(RangeThreshold);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Enabled != false) {
            size += 1 + 1;
          }
          if (RangeThreshold != 0F) {
            size += 1 + 4;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(EvasionConfig other) {
          if (other == null) {
            return;
          }
          if (other.Enabled != false) {
            Enabled = other.Enabled;
          }
          if (other.RangeThreshold != 0F) {
            RangeThreshold = other.RangeThreshold;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Enabled = input.ReadBool();
                break;
              }
              case 21: {
                RangeThreshold = input.ReadFloat();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Enabled = input.ReadBool();
                break;
              }
              case 21: {
                RangeThreshold = input.ReadFloat();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  /// <summary>
  /// Dynamic configuration.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DynamicConfig : pb::IMessage<DynamicConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DynamicConfig> _parser = new pb::MessageParser<DynamicConfig>(() => new DynamicConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DynamicConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Micromissiles.DynamicConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicConfig(DynamicConfig other) : this() {
      flightConfig_ = other.flightConfig_ != null ? other.flightConfig_.Clone() : null;
      sensorConfig_ = other.sensorConfig_ != null ? other.sensorConfig_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DynamicConfig Clone() {
      return new DynamicConfig(this);
    }

    /// <summary>Field number for the "flight_config" field.</summary>
    public const int FlightConfigFieldNumber = 1;
    private global::Micromissiles.FlightConfig flightConfig_;
    /// <summary>
    /// Flight configuration.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.FlightConfig FlightConfig {
      get { return flightConfig_; }
      set {
        flightConfig_ = value;
      }
    }

    /// <summary>Field number for the "sensor_config" field.</summary>
    public const int SensorConfigFieldNumber = 2;
    private global::Micromissiles.SensorConfig sensorConfig_;
    /// <summary>
    /// Sensor configuration.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Micromissiles.SensorConfig SensorConfig {
      get { return sensorConfig_; }
      set {
        sensorConfig_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DynamicConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DynamicConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FlightConfig, other.FlightConfig)) return false;
      if (!object.Equals(SensorConfig, other.SensorConfig)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (flightConfig_ != null) hash ^= FlightConfig.GetHashCode();
      if (sensorConfig_ != null) hash ^= SensorConfig.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (flightConfig_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FlightConfig);
      }
      if (sensorConfig_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SensorConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (flightConfig_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FlightConfig);
      }
      if (sensorConfig_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SensorConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (flightConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FlightConfig);
      }
      if (sensorConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SensorConfig);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DynamicConfig other) {
      if (other == null) {
        return;
      }
      if (other.flightConfig_ != null) {
        if (flightConfig_ == null) {
          FlightConfig = new global::Micromissiles.FlightConfig();
        }
        FlightConfig.MergeFrom(other.FlightConfig);
      }
      if (other.sensorConfig_ != null) {
        if (sensorConfig_ == null) {
          SensorConfig = new global::Micromissiles.SensorConfig();
        }
        SensorConfig.MergeFrom(other.SensorConfig);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (flightConfig_ == null) {
              FlightConfig = new global::Micromissiles.FlightConfig();
            }
            input.ReadMessage(FlightConfig);
            break;
          }
          case 18: {
            if (sensorConfig_ == null) {
              SensorConfig = new global::Micromissiles.SensorConfig();
            }
            input.ReadMessage(SensorConfig);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (flightConfig_ == null) {
              FlightConfig = new global::Micromissiles.FlightConfig();
            }
            input.ReadMessage(FlightConfig);
            break;
          }
          case 18: {
            if (sensorConfig_ == null) {
              SensorConfig = new global::Micromissiles.SensorConfig();
            }
            input.ReadMessage(SensorConfig);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
