# .github/workflows/docs.yaml
name: Deploy Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Updated to Node.js 18

      - name: Install dependencies
        run: npm ci
        working-directory: './docs'

      - name: Build documentation
        run: npm run docs:build
        working-directory: './docs'

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          destination_dir: docs
          allow_empty_commit: true
          keep_files: true
          force_orphan: false