name: Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  clang-format:
    name: Run clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: 19
          check-path: '.'
          fallback-style: 'Google'
          include-regex: '^.*\.((((c|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))|(ino|pde|proto|cs|cu))$'

  buildifier:
    name: Run buildifier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Buildifier
        run: |
          curl -L -o buildifier https://github.com/bazelbuild/buildtools/releases/download/5.3.0/buildifier-linux-amd64
          chmod +x buildifier
      - name: Run Buildifier Check
        run: |
          find plugins -type f \( -name "*.bazel" -o -name "*.bzl" -o -name "BUILD" \) | xargs ./buildifier -mode=check -lint=warn
