name: Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allow manual triggering.

jobs:
  clang-format:
    name: Run clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: 20
          check-path: '.'
          fallback-style: 'Google'
          exclude-regex: '^Assets\/Scripts\/Generated\/.*'

  buildifier:
    name: Run buildifier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install buildifier
        run: |
          curl -L -o /usr/local/bin/buildifier https://github.com/bazelbuild/buildtools/releases/download/v6.4.0/buildifier-linux-amd64
          chmod +x /usr/local/bin/buildifier
      - name: Run buildifier
        run: |
          find plugins -type f -name "*.bazel" -o -name "*.bzl" -o -name "BUILD" | xargs buildifier -mode=check
          find plugins -type f -name "*.bazel" -o -name "*.bzl" -o -name "BUILD" | xargs buildifier -lint=warn -mode=check
