name: Release

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-tags: true

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=${latest_tag}" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
          release_name: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
          body_path: RELEASE.md
          draft: false
          prerelease: false

      - uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Upload Windows release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: micromissiles-${{ github.event.workflow_run.head_branch }}-windows-x86_64.zip
          asset_path: build/build-StandaloneWindows64.zip
          asset_content_type: application/zip

      - name: Upload Darwin release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: micromissiles-${{ github.event.workflow_run.head_branch }}-darwin-x86_64.tar.gz
          asset_path: build/build-StandaloneOSX.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: micromissiles-${{ github.event.workflow_run.head_branch }}-linux-x86_64.tar.gz
          asset_path: build/build-StandaloneLinux64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows plugins
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: micromissiles-plugins-${{ github.event.workflow_run.head_branch }}-windows-x86_64.tar.gz
          asset_path: build/plugins-windows-latest.tar.gz
          asset_content_type: application/gzip

      - name: Upload Darwin plugins
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: micromissiles-plugins-${{ github.event.workflow_run.head_branch }}-darwin-x86_64.tar.gz
          asset_path: build/plugins-macos-latest.tar.gz
          asset_content_type: application/gzip

      - name: Upload Linux plugins
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: micromissiles-plugins-${{ github.event.workflow_run.head_branch }}-linux-x86_64.tar.gz
          asset_path: build/plugins-ubuntu-22.04.tar.gz
          asset_content_type: application/gzip
