name: Release

on:
  workflow_run:
      workflows: ['Build']
      types: [completed]
      branches:
          - release

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: .github/workflows/release.md
          draft: false
          prerelease: false
