name: Release

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'v')
    steps:
      - name: Validate semantic version tag
        run: |
          if [[ ! "${{ github.event.workflow_run.head_branch }}" =~ v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "Error: Branch name ${{ github.event.workflow_run.head_branch }} does not match semantic version pattern."
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-tags: true

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=${latest_tag}" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Rename build artifacts
        run: |
          mv build/build-StandaloneWindows64.zip build/micromissiles-${{ github.event.workflow_run.head_branch }}-windows-x86_64.zip
          mv build/build-StandaloneOSX.tar.gz build/micromissiles-${{ github.event.workflow_run.head_branch }}-darwin-x86_64.tar.gz
          mv build/build-StandaloneLinux64.tar.gz build/micromissiles-${{ github.event.workflow_run.head_branch }}-linux-x86_64.tar.gz

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
          name: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
          body_path: RELEASE.md
          files: |
            build/micromissiles-${{ github.event.workflow_run.head_branch }}-windows-x86_64.zip
            build/micromissiles-${{ github.event.workflow_run.head_branch }}-darwin-x86_64.tar.gz
            build/micromissiles-${{ github.event.workflow_run.head_branch }}-linux-x86_64.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
